### PR TITLE
changed core js to react with some styling issue in header and footer

### PR DESCRIPTION
**Pull request by GouravChamaria**
- added react code of core js 
- styling issues in header and footer component
- also a class "pageContent" to be added to section of all pages components
- used react-vite

### CODE REVIEW

**Review by GouravChamaria — COMMENTED** [review]
- fixed styling issues
- deleted old files

**Comment by di1ara** [comment]
looks good!

**Review by di1ara — APPROVED** [review]

**Review by iamzoltan — APPROVED** [review]
Looks great! Good work.

Refactoring suggestion:
We could think about having a Layout component that handles the footer and header and then wrap each page with the layout.

**Comment by quhdoos** [comment]
Looks like a good starting point!

**Review by kiduswb — APPROVED** [review]

**Pull request merged**
